export const authenticationActions = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT"
};

export const canvasActions = {
  CANVAS_CREATE_REQUEST: "CANVAS_CREATE_REQUEST",
  CANVAS_CREATE_SUCCESS: "CANVAS_CREATE_SUCCESS",
  CANVAS_CREATE_FAILURE: "CANVAS_CREATE_FAILURE",
};

export const currentUserActions = {
  CURRENT_USER_REQUEST: "CURRENT_USER_REQUEST",
  CURRENT_USER_SUCCESS: "CURRENT_USER_SUCCESS",
  CURRENT_USER_FAILURE: "CURRENT_USER_FAILURE",
};

export const uiActions = { TOGGLE_FORM: "TOGGLE_FORM" };
